name = "balaji-portfolio"
main = "index.html"
compatibility_date = "2024-11-01"
account_id = "<YOUR_ACCOUNT_ID>"

[site]
bucket = "./"
entry-point = "workers-site"

[build]
command = "npm run build"

[env.production]
vars = { ENVIRONMENT = "production" }
